name: ooi-on-bco-dmo
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Additional packages below
  - ipython
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - statsmodels
  - plotly
  - pip:
    - cmocean
    - python-dotenv
    - mkdocs
    - -e .
